#!/bin/bash

# This script copies a file to the ~/.local/bin directory
# If a source file is not provided as a command-line argument, the script will find the most recently modified file in the current directory
# If the destination file already exists and is newer than the source file, 
# the script will prompt the user for confirmation before overwriting it

# Function to prompt the user for confirmation
confirm_overwrite() {
    read -p "The destination file '$1' is newer than the source file. Do you want to overwrite it? [y/n]: " overwrite_confirm
    if [ "$overwrite_confirm" != "y" ]; then
        echo "Operation aborted."
        exit 1
    fi
}

# Check if command-line argument is provided
if [ -n "$1" ]; then
    source_file="$1"
else
    # Find the most recently modified file in the current directory
    source_file=$(find . -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
fi

# Specify the destination directory where you want to copy the file
destination_directory="$HOME/.local/bin"

# Get the destination file path
destination_file="$destination_directory$(basename "$source_file")"

if [ -e "$destination_file" ]; then
    # Check if the destination file is newer than the source file
    if [ "$source_file" -ot "$destination_file" ]; then
        confirm_overwrite "$destination_file"
    fi
fi

# Copy the source file to the destination directory
cp "$source_file" "$destination_directory"

echo "Copied $source_file to $destination_directory"
