#!/bin/bash

# This script copies a file to the ~/.local/bin directory
# If a source file is not provided as a command-line argument, the script will find the most recently modified file in the current directory
# If the destination file already exists and is newer than the source file, 
# the script will prompt the user for confirmation before overwriting it

# Command: g2lb [-l] [source_file]

COPY_OR_LINK="copy"

parse_args() {
    if [ "$1" == "-l" ]; then
        COPY_OR_LINK="link"
        # pop the first argument
        shift
    fi
    if [ -z "$1" ]; then
        source_file=$(ls -t | head -1)
        echo "Inferred newest file: $source_file"
        ls -l $source_file
    else
        source_file="$1"
    fi
}

# Function to prompt the user for confirmation
confirm_overwrite() {
    read -p "The destination file '$1' is newer than the source file. Do you want to overwrite it? [y/n]: " overwrite_confirm
    if [ "$overwrite_confirm" != "y" ]; then
        echo "Operation aborted."
        exit 1
    fi
}

do_link() {
    # delete the destination file if it exists
    file_exists=$( [ -f "/Users/mmigdol/.local/bin/c2lb" ] && echo "1" )
    link_exists=$( [ -h "/Users/mmigdol/.local/bin/c2lb" ] && echo "1" )
    if [ -n "$file_exists" ] || [ -n "$link_exists" ]; then
        echo "Deleting $destination_file"
        rm -f "$destination_file"
    fi
    ln -s "$(pwd)/$source_file" "$destination_file"
    echo "Linked $source_file to $destination_directory"
}

do_copy() {
    # Check if the destination file exists and is newer than the source file
    if [ -e "$destination_file" ]; then
        if [ "$source_file" -ot "$destination_file" ]; then
            confirm_overwrite "$destination_file"
        fi
    fi
    # Copy the file to the destination directory
    cp "$source_file" "$destination_directory"
    echo "Copied $source_file to $destination_directory"
}

parse_args "$@"

# Specify the destination directory where you want to copy the file
destination_directory="$HOME/.local/bin"

# Get the destination file path
destination_file="$destination_directory/$(basename "$source_file")"
if [ "$COPY_OR_LINK" == "link" ]; then
    do_link
    exit 0
fi
do_copy


