#!/usr/bin/env bash
# Generates an ascii tree of the git repo, excluding files in .gitignore

# tree is not installed by default on macOS - install if not found
if ! [ -x "$(command -v tree)" ];
then
    # check if Mac
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "tree not found - installing with brew"
        brew install tree
    else
        echo "tree not found - please install manually"
        exit 1
    fi
fi

# Read .gitignore file and construct list of -I clauses
exclude_patterns=""
while IFS= read -r line; do
  if [[ $line != "" && $line != \#* ]]; then  # Exclude empty lines and comments
    exclude_patterns+=" -I '$line'"
  fi
done < .gitignore

# Generate tree diagram with exclusion patterns
eval "tree $exclude_patterns ."